package com.example.t00063414.tourguideapp;

/**
 * Created by t00063414 on 10/17/2016.
 */
public class ReturnData {

    public String[] StringArray(){

        String newfoundland = "Newfoundland and Labrador form the most easterly province of Canada. On Newfoundland island, the Norse archaeological site L'Anse aux Meadows is the reputed settlement of Viking explorer Leif Erikson. Gros Morne National Park, on the Gulf of St Lawrence, has cliffs, waterfalls and glacial fjords. Southeastern capital city St. John’s is known for the 17th-century Signal Hill citadel, with a hillside walking trail.Newfoundland and Labrador form the most easterly province of Canada. On Newfoundland island, the Norse archaeological site L'Anse aux Meadows is the reputed settlement of Viking explorer Leif Erikson. Gros Morne National Park, on the Gulf of St Lawrence, has cliffs, waterfalls and glacial fjords. Southeastern capital city St. John’s is known for the 17th-century Signal Hill citadel, with a hillside walking trail.";
        //String newfoundland = "Newfoundland and Labrador form the most easterly province of Canada. On Newfoundland island, the Norse archaeological site L'Anse aux Meadows is the reputed settlement of Viking explorer Leif Erikson. Gros Morne National Park, on the Gulf of St Lawrence, has cliffs, waterfalls and glacial fjords. Southeastern capital city St. John’s is known for the 17th-century Signal Hill citadel, with a hillside walking trail.";
        String Ontario= "Ontario is a province in east-central Canada that borders the U.S. and the Great Lakes. It's home to Ottawa, Canada's capital, known for Parliament Hill’s Victorian architecture and the National Gallery, featuring Canadian and indigenous art. Toronto, Ontario's capital, is home to the 553m-high CN Tower, with expansive views from its revolving restaurant, as well as High Park, site of a rare oak savannah habitat.";
        String BritishColumbia= "British Columbia, Canada's westernmost province, is defined by its Pacific coastline and mountain ranges. Nature areas like Glacier National Park offer hiking and biking trails, as well as campgrounds. Whistler Blackcomb is a major ski resort that hosted the 2010 Winter Olympics. The scenic Sea-to-Sky Highway links Whistler with Vancouver, a city known for its film industry, at the province's southern U.S. border.";
        String Alberta= "Alberta is a province in Western Canada. Its landscape encompasses mountains, prairies, desert badlands and vast coniferous forests. It has more than 600 lakes, and rich mineral deposits. In the west, the Canadian Rocky Mountain Parks have glaciers in the Columbia Icefields. The Waterton Glacier International Peace Park is a biosphere reserve that straddles the southern border with the USA.";
        String Quebec= "Québec is a predominantly French-speaking province in eastern Canada with 2 vibrant cities in its south, connected by the Chemin du Roy highway along the Saint Lawrence River. The metropolis Montréal is named after Mt. Royal, the triple-peaked hill at its heart. Dating to 1608, Québec City retains its old colonial core, Place Royale, and historic harbor, Vieux Port, now known for nightlife.";
        String NovaScotia= "Nova Scotia is one of eastern Canada's Maritime provinces on the Atlantic. Consisting of a peninsula and offshore islands, it's home to puffins and seals, and popular for water sports like kayaking. The Bay of Fundy, with its famously extreme tides, is a whale-watching destination. Halifax, the capital, dominated by the star-shaped Citadel, is known for its lively waterfront and Victorian-era Public Gardens.";
        String NewBrunswick= "New Brunswick is one of eastern Canada's Maritime provinces. It encompasses rivers, pine forest, mountains and the Bay of Fundy, known for extreme tides and whale-watching. The port city of St. John is home to the New Brunswick Museum, with local artwork dating to the 1800s, and the long-standing St. John City Market's many food stalls. To the southwest is Reversing Falls, where rapids flow backwards at high tide.";
        String PrinceEdwardIsland= "Prince Edward Island is one of eastern Canada's maritime provinces, off New Brunswick and Nova Scotia in the Gulf of St. Lawrence. The large island is marked by red-sand beaches, lighthouses, and fertile farmland, and is renowned for seafood like lobster and mussels. Charlottetown, the capital, is home to Victorian government buildings & the modern Confederation Centre of the Arts, with a theatre and art gallery.";
        String Saskatchewan= "Saskatchewan is a Canadian province that borders the United States to the south. Grassland covers its southern plains, and to the north are the rugged rock of the Canadian Shield plateau, coniferous forests, rivers and lakes. Regina, the provincial capital, is home to the Royal Saskatchewan Museum, with exhibits on natural history and the people of Canada’s First Nations.";

        String [] dataArray = new String[]{newfoundland, Ontario,BritishColumbia, Alberta, Quebec, NovaScotia, NewBrunswick, PrinceEdwardIsland, Saskatchewan};
      return dataArray;
    }
}
